<?xml version="1.0"?>
<package format="3">
  <name>ekf_se3_localization</name>
  <version>0.1.0</version>
  <description>EKF map-based localization on SE(3) with Gazebo Ackermann car simulation</description>
  <maintainer email="a.solares88@gmail.com">gui</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>geometry_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>tf2</depend>
  <depend>tf2_ros</depend>
  <depend>tf2_eigen</depend>
  <depend>sensor_msgs</depend>
  <depend>ros_gz_sim</depend>
  <depend>ros_gz_bridge</depend>
  <exec_depend>rosgraph_msgs</exec_depend>

  <build_depend>sophus</build_depend>
  <exec_depend>sophus</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
